# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(max_length=7, unique=True)),
                ('cname', models.CharField(default='', max_length=30)),
                ('teacher', models.CharField(default='', max_length=30)),
                ('credit', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('cancel_year', models.IntegerField(null=True)),
            ],
        ),
    ]
