# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Select',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_year', models.IntegerField()),
                ('score', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.Course')),
                ('sid', models.ManyToManyField(to='APP.Student')),
            ],
        ),
    ]
