# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_auto_20170429_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='select',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='select',
            name='sid',
        ),
    ]
