# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0010_auto_20170429_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='select',
            old_name='cid',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='select',
            name='sid',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(null=True, through='APP.Select', to='APP.Student'),
        ),
        migrations.AddField(
            model_name='select',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='APP.Student'),
            preserve_default=False,
        ),
    ]
