# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0011_auto_20170429_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='APP.Select', to='APP.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sid',
            field=models.IntegerField(unique=True),
        ),
    ]
